/* eslint-disable react-hooks/rules-of-hooks */
/* CollectionReceiptDialog.tsx */
"use client";

import React, { useRef, useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { PremiumCollectionData } from "../interface";
import { toWords } from "number-to-words";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  data: PremiumCollectionData | null;
}

const CollectionReceiptDialog: React.FC<Props> = ({
  open,
  onOpenChange,
  data,
}) => {
  const receiptRef = useRef<HTMLDivElement>(null);
  const [imagesLoaded, setImagesLoaded] = useState(false);

  if (!data) return null;

  // Wait until all images in the receipt are loaded
  useEffect(() => {
    if (!open) return;
    const images = receiptRef.current?.querySelectorAll("img") || [];
    let loaded = 0;
    const checkLoaded = () => {
      loaded++;
      if (loaded === images.length) setImagesLoaded(true);
    };
    images.forEach((img) => {
      if ((img as HTMLImageElement).complete) checkLoaded();
      else img.addEventListener("load", checkLoaded);
    });
    if (images.length === 0) setImagesLoaded(true);
  }, [open]);

  const formatDate = (dateStr: string | undefined) => {
    if (!dateStr) return "-";
    const date = new Date(dateStr);
    return date.toLocaleDateString("en-GB");
  };

  const handleDownloadPDF = async () => {
    if (!receiptRef.current || !imagesLoaded) return;

    const canvas = await html2canvas(receiptRef.current, {
      scale: 3,
      useCORS: true,
      backgroundColor: "#ffffff",
      allowTaint: true,
      onclone: (clonedDoc) => {
        clonedDoc.querySelectorAll("*").forEach((el) => {
          const e = el as HTMLElement;
          const styles = getComputedStyle(e);
          e.style.color = styles.color.replace(/lab\(.*?\)/, "rgb(0,0,0)");
          e.style.backgroundColor = styles.backgroundColor.replace(
            /lab\(.*?\)/,
            "rgb(255,255,255)"
          );
          e.style.borderColor = styles.borderColor.replace(/lab\(.*?\)/, "rgb(0,0,0)");
          e.style.boxShadow = "none";
          e.style.textShadow = "none";
          e.style.fontFamily = "Arial, sans-serif";
        });
      },
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");

    const pageWidth = 210;
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);
    pdf.save(`collection-${data.policy.policy_no}.pdf`);
  };

  const receiptHeightMm = 97;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="min-w-[850px] max-h-screen overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="w-full bg-blue-600 text-white p-4 rounded-md text-center">
            Collection Receipt
          </DialogTitle>
        </DialogHeader>

        <div
          ref={receiptRef}
          className="w-[210mm] bg-white"
          style={{ minHeight: "297mm" }}
        >
          {[0, 1, 2].map((_, i) => (
            <div
              key={i}
              className="border border-dashed border-black mb-[0.5mm] p-[5mm] flex flex-col justify-between text-[12px]"
              style={{ height: `${receiptHeightMm}mm` }}
            >
              {/* Header */}
              <div className="flex justify-center mb-[5mm]">
                <img
                  src="/images/assets/headers.jpg"
                  alt="Header"
                  className="w-[250px] h-[50px]"
                />
              </div>

              {/* Receipt content */}
              <div className="flex-1 leading-6">
                <div className="text-center font-bold mt-1">
                  Generated By: {data.branch_code}
                </div>
                <br />
                <div className="flex justify-between mb-[2mm] text-sm">
                  <div>Receipt No: {data.accountTransaction.voucher_no}</div>
                  <div className="text-center">MONEY RECEIPT</div>
                  <div className="text-right">
                    Date: {formatDate(data.collection_date)}
                  </div>
                </div>
                <div className="border border-black mb-[2mm] flex " />
                <div className="p-4 flex flex-row flex-wrap items-center">
                  <span>
                    Received with thanks from <b>{data.policy?.policy_no ?? "-"}</b>,
                  </span>

                  {data.collectionDetails?.map((detail, idx) => {
                    const mode = detail.collection_mode?.toUpperCase();
                    return (
                      <span key={idx} className="flex items-center mx-1 whitespace-nowrap">
                        sum of Ngultrum <b>{detail.amount}</b>/-
                        ({toWords(Number(detail.amount))}) by <b>{mode}</b>
                        {mode === "CASH" && (
                          <> , dated <b>{formatDate(detail.instrument_date || data.collection_date)}</b></>
                        )}
                        {mode === "CHEQUE" && (
                          <>
                            , Cheque No <b>{detail.instrument_number || "-"}</b>,
                            Bank: <b>{detail.bank_name || "-"}</b>,
                            , dated <b>{formatDate(detail.instrument_date || data.collection_date)}</b>
                          </>
                        )}
                      </span>
                    );
                  })}

                  <span className="">
                    , being the payment of <i>Life Insurance</i>.
                  </span>
                </div>
              </div>

              <div className="text-right mt-[5mm] font-bold">Bhutan Insurance LTD.</div>

              {/* Footer */}
              <div className="flex justify-center items-center">
                <img
                  src="/images/assets/footer.jpg"
                  alt="Footer"
                  className="w-[250px] h-[50px]"
                />
              </div>
            </div>
          ))}
        </div>

        <div className="flex justify-end gap-2 mt-4">
          <Button
            className="bg-red-500 text-white"
            onClick={() => onOpenChange(false)}
          >
            Close
          </Button>
          <Button
            className="bg-blue-600 text-white"
            onClick={handleDownloadPDF}
          >
            Download PDF
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default CollectionReceiptDialog;