export const tourData = {
  North: [
    {
      id: 1,
      name: "Himachal Pradesh Tour Data",
      tours: 33,
      image:
        "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    },
    {
      id: 2,
      name: "Jammu And Kashmir Tour Data",
      tours: 24,
      image:
        "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    },
    {
      id: 3,
      name: "Leh Ladakh Tour Data",
      tours: 23,
      image:
        "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=600&q=80",
    },
    {
      id: 4,
      name: "Nainital Mussoorie Corbett Tour Data",
      tours: 17,
      image:
        "https://images.unsplash.com/photo-1575408264798-b50b252663e6?w=600&q=80",
    },
    {
      id: 5,
      name: "Amritsar Tour Data",
      tours: 13,
      image:
        "https://images.unsplash.com/photo-1588416498473-da72fb5e3e9c?w=600&q=80",
    },
    {
      id: 6,
      name: "Agra Tour Data",
      tours: 15,
      image:
        "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    },
    {
      id: 7,
      name: "Delhi Tour Data",
      tours: 30,
      image:
        "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&q=80",
    },
    {
      id: 8,
      name: "Uttarakhand Tour Data",
      tours: 21,
      image:
        "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=600&q=80",
    },
  ],
  South: [
    {
      id: 1,
      name: "Kerala Tour Data",
      tours: 40,
      image:
        "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    },
    {
      id: 2,
      name: "Tamil Nadu Tour Data",
      tours: 28,
      image:
        "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
    },
    {
      id: 3,
      name: "Karnataka Tour Data",
      tours: 22,
      image:
        "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&q=80",
    },
    {
      id: 4,
      name: "Andhra Pradesh Tour Data",
      tours: 18,
      image:
        "https://images.unsplash.com/photo-1563135893-bcd95c13e74f?w=600&q=80",
    },
  ],
  "West & Central": [
    {
      id: 1,
      name: "Rajasthan Tour Data",
      tours: 45,
      image:
        "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
    },
    {
      id: 2,
      name: "Goa Tour Data",
      tours: 32,
      image:
        "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80",
    },
    {
      id: 3,
      name: "Maharashtra Tour Data",
      tours: 26,
      image:
        "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&q=80",
    },
    {
      id: 4,
      name: "Gujarat Tour Data",
      tours: 19,
      image:
        "https://images.unsplash.com/photo-1563135893-bcd95c13e74f?w=600&q=80",
    },
  ],
  "East & North East": [
    {
      id: 1,
      name: "West Bengal Tour Data",
      tours: 20,
      image:
        "https://images.unsplash.com/photo-1558431382-27e303142255?w=600&q=80",
    },
    {
      id: 2,
      name: "Sikkim Tour Data",
      tours: 16,
      image:
        "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    },
    {
      id: 3,
      name: "Assam Tour Data",
      tours: 14,
      image:
        "https://images.unsplash.com/photo-1575408264798-b50b252663e6?w=600&q=80",
    },
    {
      id: 4,
      name: "Meghalaya Tour Data",
      tours: 12,
      image:
        "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=600&q=80",
    },
  ],
};


export const tours = [
  // ─── INDIA ────────────────────────────────────────────────
  {
    id: 1,
    country: "India",
    place: "Uttarakhand",
    title: "Char Dham Yatra By Helicopter",
    type: "Pilgrimage Tour",
    duration: "6 Days / 5 Nights",
    durationTag: "6 Days",
    startEnd: "Dehradun → Dehradun",
    destinations: ["Gangotri", "Yamunotri", "Kedarnath", "Badrinath"],
    amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
    price: 230000,
    rating: 4.9,
    reviews: 312,
    badge: "Bestseller",
    badgeColor: "bg-amber-500",
    mode: "Helicopter",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&q=80",
    popular: true,
  },
  {
    id: 2,
    country: "India",
    place: "Uttarakhand",
    title: "Chardham Yatra Package from Delhi",
    type: "Pilgrimage Tour",
    duration: "11 Days / 12 Nights",
    durationTag: "12 Days",
    startEnd: "Delhi → Badrinath",
    destinations: ["Gangotri", "Yamunotri", "Kedarnath", "Badrinath"],
    amenities: ["Hotel", "Meals", "Transfers", "Kumbh Snan"],
    price: 43900,
    rating: 4.9,
    reviews: 428,
    badge: "Bestseller",
    badgeColor: "bg-amber-500",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=640&q=80",
    popular: true,
  },
  {
    id: 3,
    country: "India",
    place: "Srinagar",
    title: "Amarnath Yatra Packages",
    type: "Pilgrimage Tour",
    duration: "Multi-Day",
    durationTag: "Multi-Day",
    startEnd: "Srinagar → Amarnath Cave",
    destinations: ["Srinagar", "Pahalgam", "Panjtarni", "Amarnath Cave"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 25900,
    rating: 4.8,
    reviews: 197,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=640&q=80",
    popular: true,
  },
  {
    id: 4,
    country: "India",
    place: "Uttarakhand",
    title: "Adi Kailash & Om Parvat Yatra",
    type: "Pilgrimage Tour",
    duration: "Multi-Day",
    durationTag: "Multi-Day",
    startEnd: "Haldwani → Adi Kailash",
    destinations: ["Haldwani", "Dharchula", "Gunji", "Kalapani", "Adi Kailash"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 48500,
    rating: 4.8,
    reviews: 83,
    badge: "Premium",
    badgeColor: "bg-sky-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=640&q=80",
    popular: false,
  },
  {
    id: 5,
    country: "India",
    place: "Delhi",
    title: "Golden Triangle Tour Package",
    type: "Cultural Tour",
    duration: "Multi-Day",
    durationTag: "Multi-Day",
    startEnd: "Delhi → Amritsar",
    destinations: ["Delhi", "Agra", "Mathura", "Jaipur", "Amritsar"],
    amenities: ["Hotel", "Meals", "Transfers", "Guided Tours"],
    price: 12500,
    rating: 4.7,
    reviews: 534,
    badge: "Bestseller",
    badgeColor: "bg-amber-500",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=640&q=80",
    popular: true,
  },
  {
    id: 6,
    country: "India",
    place: "Bhubaneswar",
    title: "Bhubaneswar Puri Konark Tour",
    type: "Temple Tour",
    duration: "4 Days / 3 Nights",
    durationTag: "4 Days",
    startEnd: "Bhubaneswar → Puri",
    destinations: ["Bhubaneswar", "Konark", "Puri"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 12900,
    rating: 4.6,
    reviews: 142,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=640&q=80",
    popular: true,
  },
  {
    id: 7,
    country: "India",
    place: "Guwahati",
    title: "Kamakhya Devi Temple Tour",
    type: "Pilgrimage Tour",
    duration: "3 Days / 2 Nights",
    durationTag: "3 Days",
    startEnd: "Guwahati → Guwahati",
    destinations: ["Guwahati", "Kamakhya Temple"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 13500,
    rating: 4.7,
    reviews: 118,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=640&q=80",
    popular: true,
  },
  {
    id: 8,
    country: "India",
    place: "Varanasi",
    title: "Varanasi Ayodhya Bodhgaya Chitrakoot Tour",
    type: "Pilgrimage Tour",
    duration: "7 Days / 6 Nights",
    durationTag: "7 Days",
    startEnd: "Varanasi → Chitrakoot",
    destinations: ["Varanasi", "Bodhgaya", "Ayodhya", "Chitrakoot"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 32500,
    rating: 4.7,
    reviews: 176,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=640&q=80",
    popular: true,
  },
  {
    id: 9,
    country: "India",
    place: "Ahmedabad",
    title: "Pancha Dwaraka Tour from Ahmedabad",
    type: "Pilgrimage Tour",
    duration: "10 Days / 9 Nights",
    durationTag: "10 Days",
    startEnd: "Ahmedabad → Somnath",
    destinations: ["Ahmedabad", "Dwarka", "Porbandar", "Somnath"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 42900,
    rating: 4.6,
    reviews: 93,
    badge: "Heritage",
    badgeColor: "bg-orange-500",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=640&q=80",
    popular: false,
  },
  {
    id: 10,
    country: "India",
    place: "Chennai",
    title: "Tamil Nadu Temple Tour from Chennai",
    type: "Temple Tour",
    duration: "8 Days / 7 Nights",
    durationTag: "8 Days",
    startEnd: "Chennai → Trichy",
    destinations: ["Chennai", "Pondicherry", "Chidambaram", "Rameswaram", "Kanyakumari", "Madurai", "Trichy"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 38900,
    rating: 4.7,
    reviews: 214,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=640&q=80",
    popular: true,
  },
  {
    id: 11,
    country: "India",
    place: "Port Blair",
    title: "Andaman Island Retreat",
    type: "Island Tour",
    duration: "6 Days / 5 Nights",
    durationTag: "6 Days",
    startEnd: "Port Blair → Havelock",
    destinations: ["Port Blair", "Havelock Island", "Elephant Beach"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 39000,
    rating: 4.8,
    reviews: 267,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Ferry",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=640&q=80",
    popular: true,
  },
  {
    id: 12,
    country: "India",
    place: "Leh",
    title: "Ladakh Adventure Tour",
    type: "Adventure Tour",
    duration: "10 Days / 9 Nights",
    durationTag: "10 Days",
    startEnd: "Srinagar → Leh",
    destinations: ["Srinagar", "Gulmarg", "Sonmarg", "Leh", "Pangong Tso"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 70000,
    rating: 4.9,
    reviews: 189,
    badge: "Adventure",
    badgeColor: "bg-emerald-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=640&q=80",
    popular: true,
  },
  {
    id: 13,
    country: "India",
    place: "Gangtok",
    title: "Sikkim & Darjeeling Holiday",
    type: "Hill Station Tour",
    duration: "6 Days / 5 Nights",
    durationTag: "6 Days",
    startEnd: "Kalimpong → Darjeeling",
    destinations: ["Kalimpong", "Gangtok", "Darjeeling"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 35000,
    rating: 4.7,
    reviews: 154,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=640&q=80",
    popular: true,
  },
  {
    id: 14,
    country: "India",
    place: "Jaipur",
    title: "Royal Rajasthan Tour",
    type: "Heritage Tour",
    duration: "10 Days / 9 Nights",
    durationTag: "10 Days",
    startEnd: "Jaipur → Pushkar",
    destinations: ["Jaipur", "Bikaner", "Jaisalmer", "Jodhpur", "Udaipur", "Mount Abu", "Pushkar"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 78000,
    rating: 4.8,
    reviews: 302,
    badge: "Luxury",
    badgeColor: "bg-purple-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=640&q=80",
    popular: true,
  },
  {
    id: 15,
    country: "India",
    place: "Shirdi",
    title: "Shirdi – Bhimashankar Pilgrimage Tour",
    type: "Pilgrimage Tour",
    duration: "6 Days / 5 Nights",
    durationTag: "6 Days",
    startEnd: "Shirdi → Bhimashankar",
    destinations: ["Shirdi", "Bhimashankar"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 26000,
    rating: 4.6,
    reviews: 107,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=640&q=80",
    popular: false,
  },
  {
    id: 16,
    country: "India",
    place: "Pan India",
    title: "Jyotirlinga Darshan Yatra",
    type: "Pilgrimage Tour",
    duration: "20 Days / 19 Nights",
    durationTag: "20 Days",
    startEnd: "Delhi → Delhi",
    destinations: ["Somnath", "Mallikarjuna", "Mahakaleshwar", "Omkareshwar", "Kedarnath", "Bhimashankar", "Kashi", "Trimbakeshwar", "Vaidyanath", "Nageshwar", "Rameshwaram", "Grishneshwar"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 110000,
    rating: 4.9,
    reviews: 241,
    badge: "Bestseller",
    badgeColor: "bg-amber-500",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=640&q=80",
    popular: true,
  },
  {
    id: 17,
    country: "India",
    place: "Khajuraho",
    title: "Khajuraho – Orchha Temple Tour",
    type: "Heritage Tour",
    duration: "5 Days / 4 Nights",
    durationTag: "5 Days",
    startEnd: "Khajuraho → Jhansi",
    destinations: ["Khajuraho", "Orchha", "Jhansi"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 21000,
    rating: 4.6,
    reviews: 88,
    badge: "Heritage",
    badgeColor: "bg-orange-500",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=640&q=80",
    popular: false,
  },
  {
    id: 18,
    country: "India",
    place: "Chennai",
    title: "Rameshwaram Madurai Kanyakumari Tour",
    type: "Temple Tour",
    duration: "6 Days / 5 Nights",
    durationTag: "6 Days",
    startEnd: "Chennai → Trivandrum",
    destinations: ["Chennai", "Mahabalipuram", "Tanjore", "Trichy", "Madurai", "Rameshwaram", "Kanyakumari", "Trivandrum"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 42000,
    rating: 4.7,
    reviews: 196,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=640&q=80",
    popular: true,
  },

  // ─── INTERNATIONAL ────────────────────────────────────────
  {
    id: 19,
    country: "Vietnam",
    place: "Hanoi",
    title: "Vietnam Tour Packages",
    type: "Cultural Tour",
    duration: "Multi-Day",
    durationTag: "Multi-Day",
    startEnd: "Hanoi → Ho Chi Minh City",
    destinations: ["Hanoi", "Ninh Binh", "Halong Bay", "Da Nang", "Hoi An", "Ho Chi Minh City", "Mekong Delta"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 18500,
    rating: 4.7,
    reviews: 143,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?w=640&q=80",
    popular: true,
  },
  {
    id: 20,
    country: "Sri Lanka",
    place: "Colombo",
    title: "Sri Lanka Ramayana Tour",
    type: "Cultural Tour",
    duration: "8 Days / 7 Nights",
    durationTag: "8 Days",
    startEnd: "Anuradhapura → Colombo",
    destinations: ["Anuradhapura", "Trincomalee", "Kandy", "Nuwara Eliya", "Kataragama", "Colombo"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 34900,
    rating: 4.8,
    reviews: 178,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=640&q=80",
    popular: true,
  },
  {
    id: 21,
    country: "Indonesia",
    place: "Bali",
    title: "Bali Tour Packages",
    type: "Beach Tour",
    duration: "Multi-Day",
    durationTag: "Multi-Day",
    startEnd: "Ubud → Seminyak",
    destinations: ["Ubud", "Kuta", "Denpasar", "Seminyak", "Tegalalang Rice Terrace"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 16500,
    rating: 4.7,
    reviews: 389,
    badge: "Bestseller",
    badgeColor: "bg-amber-500",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=640&q=80",
    popular: true,
  },
  {
    id: 22,
    country: "UAE",
    place: "Dubai",
    title: "Dubai Tour Packages",
    type: "Luxury Tour",
    duration: "Multi-Day",
    durationTag: "Multi-Day",
    startEnd: "Dubai → Abu Dhabi",
    destinations: ["Dubai", "Desert Safari", "Dhow Cruise", "Abu Dhabi"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 26500,
    rating: 4.8,
    reviews: 456,
    badge: "Bestseller",
    badgeColor: "bg-amber-500",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=640&q=80",
    popular: true,
  },
  {
    id: 23,
    country: "Egypt",
    place: "Cairo",
    title: "Egypt Tour Packages",
    type: "Heritage Tour",
    duration: "Multi-Day",
    durationTag: "Multi-Day",
    startEnd: "Cairo → Sinai Peninsula",
    destinations: ["Cairo", "Nile River Valley", "Red Sea", "Sinai Peninsula"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 45500,
    rating: 4.8,
    reviews: 162,
    badge: "Premium",
    badgeColor: "bg-sky-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=640&q=80",
    popular: true,
  },
  {
    id: 24,
    country: "Nepal",
    place: "Kathmandu",
    title: "Muktinath Yatra (Nepal)",
    type: "Pilgrimage Tour",
    duration: "7 Days / 6 Nights",
    durationTag: "7 Days",
    startEnd: "Kathmandu → Muktinath",
    destinations: ["Kathmandu", "Pokhara", "Jomsom", "Muktinath"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 51000,
    rating: 4.8,
    reviews: 134,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=640&q=80",
    popular: true,
  },
  {
    id: 25,
    country: "Nepal/Tibet",
    place: "Tibet",
    title: "Kailash Mansarovar Yatra",
    type: "Pilgrimage Tour",
    duration: "12 Days / 11 Nights",
    durationTag: "12 Days",
    startEnd: "Delhi → Mansarovar",
    destinations: ["Delhi", "Kathmandu", "Nyalam", "Kailash", "Mansarovar"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 220000,
    rating: 4.9,
    reviews: 97,
    badge: "Luxury",
    badgeColor: "bg-purple-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&q=80",
    popular: true,
  },
  {
    id: 26,
    country: "Maldives",
    place: "Male",
    title: "Maldives Honeymoon & Leisure",
    type: "Honeymoon Tour",
    duration: "5 Days / 4 Nights",
    durationTag: "5 Days",
    startEnd: "Male → Resort Island",
    destinations: ["Male", "Resort Island"],
    amenities: ["Resort", "Meals", "Transfers", "Sightseeing"],
    price: 87000,
    rating: 4.9,
    reviews: 278,
    badge: "Honeymoon",
    badgeColor: "bg-pink-500",
    mode: "Speedboat",
    img: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=640&q=80",
    popular: true,
  },
  {
    id: 27,
    country: "Singapore",
    place: "Singapore",
    title: "Singapore Family Tour",
    type: "Family Tour",
    duration: "6 Days / 5 Nights",
    durationTag: "6 Days",
    startEnd: "Singapore → Sentosa Island",
    destinations: ["Singapore City", "Sentosa Island"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 60000,
    rating: 4.8,
    reviews: 213,
    badge: "Family",
    badgeColor: "bg-teal-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=640&q=80",
    popular: true,
  },
  {
    id: 28,
    country: "Thailand",
    place: "Bangkok",
    title: "Thailand Holiday Tour",
    type: "Beach Tour",
    duration: "5 Days / 4 Nights",
    durationTag: "5 Days",
    startEnd: "Bangkok → Pattaya",
    destinations: ["Bangkok", "Pattaya"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 46000,
    rating: 4.7,
    reviews: 341,
    badge: "Popular",
    badgeColor: "bg-blue-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=640&q=80",
    popular: true,
  },
  {
    id: 29,
    country: "Japan",
    place: "Tokyo",
    title: "Japan Experience Tour",
    type: "Cultural Tour",
    duration: "9 Days / 8 Nights",
    durationTag: "9 Days",
    startEnd: "Tokyo → Osaka",
    destinations: ["Tokyo", "Hakone", "Kyoto", "Osaka"],
    amenities: ["Hotel", "Meals", "Transfers", "Sightseeing"],
    price: 133000,
    rating: 4.9,
    reviews: 187,
    badge: "Premium",
    badgeColor: "bg-sky-600",
    mode: "Train",
    img: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=640&q=80",
    popular: true,
  },
  {
    id: 30,
    country: "Mauritius",
    place: "Mauritius",
    title: "Mauritius Luxury Tour",
    type: "Luxury Tour",
    duration: "6 Days / 5 Nights",
    durationTag: "6 Days",
    startEnd: "North Island → South Island",
    destinations: ["North Island", "South Island"],
    amenities: ["Resort", "Meals", "Transfers", "Sightseeing"],
    price: 100000,
    rating: 4.8,
    reviews: 156,
    badge: "Luxury",
    badgeColor: "bg-purple-600",
    mode: "Road",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=640&q=80",
    popular: true,
  },

  // ─── HELICOPTER PACKAGES ──────────────────────────────────
 {
  id: 31,
  country: "India",
  place: "Dehradun",
  title: "Chardham Yatra By Helicopter",
  type: "Customized Holiday",
  duration: "6 Days / 5 Nights",
  durationTag: "6 Days",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Gangotri", "Yamunotri", "Kedarnath", "Badrinath"],
  amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
  price: 230000,
  rating: 4.9,
  reviews: 298,
  badge: "Bestseller",
  badgeColor: "bg-amber-500",
  mode: "Helicopter",
  img: "https://images.unsplash.com/photo-1545552987-720aa18145ca?w=640&q=80",
  popular: true,
},
{
  id: 32,
  country: "India",
  place: "Dehradun",
  title: "Chardham Yatra By Caps",
  type: "Customized Holiday",
  duration: "6 Days / 5 Nights",
  durationTag: "6 Days",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Gangotri", "Yamunotri", "Kedarnath", "Badrinath"],
  amenities: ["Hotel", "Meals", "Caps", "Sightseeing"],
  price: 43000,
  rating: 4.9,
  reviews: 298,
  badge: "Bestseller",
  badgeColor: "bg-amber-500",
  mode: "Caps",
  img: "https://images.unsplash.com/photo-1545552987-720aa18145ca?w=640&q=80",
  popular: true,
},
{
  id: 33,
  country: "India",
  place: "Dehradun",
  title: "Badri Kedar Yatra By Helicopter",
  type: "Customized Holiday",
  duration: "3 Days / 2 Nights",
  durationTag: "3 Days",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Dehradun", "Kedarnath", "Badrinath"],
  amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
  price: 140000,
  rating: 4.8,
  reviews: 164,
  badge: "Popular",
  badgeColor: "bg-blue-600",
  mode: "Helicopter",
  img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=640&q=80",
  popular: true,
},
{
  id: 34,
  country: "India",
  place: "Dehradun",
  title: "Badri Kedar Yatra By Caps",
  type: "Customized Holiday",
  duration: "3 Days / 2 Nights",
  durationTag: "3 Days",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Dehradun", "Kedarnath", "Badrinath"],
  amenities: ["Hotel", "Meals", "Caps", "Sightseeing"],
  price: 43000,
  rating: 4.8,
  reviews: 164,
  badge: "Popular",
  badgeColor: "bg-blue-600",
  mode: "Caps",
  img: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=640&q=80",
  popular: true,
},
{
  id: 35,
  country: "India",
  place: "Dehradun",
  title: "Badrinath Kedarnath Yatra By Helicopter",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Dehradun", "Badrinath", "Kedarnath"],
  amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
  price: 135000,
  rating: 4.9,
  reviews: 186,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Helicopter",
  img: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=640&q=80",
  popular: true,
},
{
  id: 36,
  country: "India",
  place: "Dehradun",
  title: "Badrinath Kedarnath Yatra By Caps",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Dehradun", "Badrinath", "Kedarnath"],
  amenities: ["Hotel", "Meals", "Caps", "Sightseeing"],
  price: 48000,
  rating: 4.9,
  reviews: 186,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Caps",
  img: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=640&q=80",
  popular: true,
},
{
  id: 37,
  country: "India",
  place: "Haridwar",
  title: "Badrinath Yatra By Helicopter",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Haridwar → Haridwar",
  destinations: ["Haridwar", "Dehradun", "Badrinath"],
  amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
  price: 85000,
  rating: 4.7,
  reviews: 112,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Helicopter",
  img: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=640&q=80",
  popular: false,
},
{
  id: 38,
  country: "India",
  place: "Haridwar",
  title: "Badrinath Yatra By Caps",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Haridwar → Haridwar",
  destinations: ["Haridwar", "Dehradun", "Badrinath"],
  amenities: ["Hotel", "Meals", "Caps", "Sightseeing"],
  price: 39000,
  rating: 4.7,
  reviews: 112,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Caps",
  img: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=640&q=80",
  popular: false,
},
{
  id: 39,
  country: "India",
  place: "Dehradun",
  title: "Kedarnath Yatra By Helicopter",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Phata", "Guptkashi", "Kedarnath"],
  amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
  price: 85000,
  rating: 4.8,
  reviews: 231,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Helicopter",
  img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&q=80",
  popular: true,
},
{
  id: 40,
  country: "India",
  place: "Dehradun",
  title: "Kedarnath Yatra By Caps",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Phata", "Guptkashi", "Kedarnath"],
  amenities: ["Hotel", "Meals", "Caps", "Sightseeing"],
  price: 25000,
  rating: 4.8,
  reviews: 231,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Caps",
  img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&q=80",
  popular: true,
},
{
  id: 41,
  country: "India",
  place: "Dehradun",
  title: "Gangotri Yatra By Helicopter",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Dehradun", "Gangotri"],
  amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
  price: 80000,
  rating: 4.7,
  reviews: 89,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Helicopter",
  img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=640&q=80",
  popular: false,
},
{
  id: 42,
  country: "India",
  place: "Dehradun",
  title: "Gangotri Yatra By Caps",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Dehradun → Dehradun",
  destinations: ["Dehradun", "Gangotri"],
  amenities: ["Hotel", "Meals", "Caps", "Sightseeing"],
  price: 22000,
  rating: 4.7,
  reviews: 89,
  badge: "Same Day",
  badgeColor: "bg-orange-500",
  mode: "Caps",
  img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=640&q=80",
  popular: false,
},
{
  id: 43,
  country: "India",
  place: "Jammu",
  title: "Vaishno Devi Yatra By Helicopter",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Jammu → Jammu",
  destinations: ["Jammu", "Sanji Chatti", "Vaishno Devi"],
  amenities: ["Hotel", "Meals", "Helicopter", "Sightseeing"],
  price: 320000,
  rating: 4.9,
  reviews: 143,
  badge: "Luxury",
  badgeColor: "bg-purple-600",
  mode: "Helicopter",
  img: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=640&q=80",
  popular: true,
},
{
  id: 44,
  country: "India",
  place: "Jammu",
  title: "Vaishno Devi Yatra By Caps",
  type: "Customized Holiday",
  duration: "Same Day (1 Day)",
  durationTag: "1 Day",
  startEnd: "Jammu → Jammu",
  destinations: ["Jammu", "Sanji Chatti", "Vaishno Devi"],
  amenities: ["Hotel", "Meals", "Caps", "Sightseeing"],
  price: 18000,
  rating: 4.9,
  reviews: 143,
  badge: "Luxury",
  badgeColor: "bg-purple-600",
  mode: "Caps",
  img: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?w=640&q=80",
  popular: true,
},
];
export const SPECIALITIES = [
  "Customized Holidays",
  "Family",
  "Women's Special",
  "Honeymoon Special",
  "Seniors' Special",
  "Road Trips",
];
export const DURATIONS = [
  "1 Day",
  "2–3 Days",
  "4–5 Days",
  "6–8 Days",
  "9+ Days",
];
export const DESTINATIONS = [
  "Delhi",
  "Dehradun",
  "Haridwar",
  "Kedarnath",
  "Badrinath",
  "Gangotri",
  "Yamunotri",
  "Chardham",
];
export const MODES = ["Helicopter", "Road", "Trek"];

export const fmt = (n: number) => "₹" + n.toLocaleString("en-IN");
